# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T02:30:07+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field


class NotificationType(Enum):
    NOTIFICATION_TYPE_UNSPECIFIED = 'NOTIFICATION_TYPE_UNSPECIFIED'
    GOOGLE_UPDATE = 'GOOGLE_UPDATE'
    NEW_REVIEW = 'NEW_REVIEW'
    UPDATED_REVIEW = 'UPDATED_REVIEW'
    NEW_CUSTOMER_MEDIA = 'NEW_CUSTOMER_MEDIA'
    NEW_QUESTION = 'NEW_QUESTION'
    UPDATED_QUESTION = 'UPDATED_QUESTION'
    NEW_ANSWER = 'NEW_ANSWER'
    UPDATED_ANSWER = 'UPDATED_ANSWER'
    DUPLICATE_LOCATION = 'DUPLICATE_LOCATION'
    LOSS_OF_VOICE_OF_MERCHANT = 'LOSS_OF_VOICE_OF_MERCHANT'
    VOICE_OF_MERCHANT_UPDATED = 'VOICE_OF_MERCHANT_UPDATED'


class NotificationSetting(BaseModel):
    name: Optional[str] = Field(
        None,
        description='Required. The resource name this setting is for. This is of the form `accounts/{account_id}/notificationSetting`.',
    )
    notificationTypes: Optional[List[NotificationType]] = Field(
        None,
        description='The types of notifications that will be sent to the Pub/Sub topic. To stop receiving notifications entirely, use NotificationSettings.UpdateNotificationSetting with an empty notification_types or set the pubsub_topic to an empty string.',
    )
    pubsubTopic: Optional[str] = Field(
        None,
        description='Optional. The Google Pub/Sub topic that will receive notifications when locations managed by this account are updated. If unset, no notifications will be posted. The account mybusiness-api-pubsub@system.gserviceaccount.com must have at least Publish permissions on the Pub/Sub topic.',
    )


class FieldXgafv(Enum):
    field_1 = '1'
    field_2 = '2'


class Alt(Enum):
    json = 'json'
    media = 'media'
    proto = 'proto'
